Feature/endpoin login mock
Darly09/barber_white_label_backend pull request #2
Opened 2023-11-06 23:24 UTC by JuanP0329

### 🎯 Milestone 

the body-parser library is installed and the mocketed endpoint for a user login is created with an MVC architecture pattern for the project implementation.

### 🛠 Changes

install the "body-parser" library and configure the index to run on port 3000 and to receive the endpoint login.

user model is created to consume login endpoint.

the user is created with a mocketed email and password and the endpoint login logic is created so that the data arrives correctly at the time of consumption.

the endpoint login is exposed with its route so that the frontend and backend can consume it where it receives the controller logic and the mocketed model.

ignore the .gitignore file

### 📘 Documentation 

- [ ] I have added or updated the documentation
- [x] No documentation update is required

### 📸 Screenshots (Opcional)

## carpeting
![image](https://github.com/Darly09/barber_white_label_backend/assets/117688239/94134139-be6f-4fec-b85e-cc54babe52b5)

## index.js configuration
![image](https://github.com/Darly09/barber_white_label_backend/assets/117688239/2ec2d5e6-3341-40ff-ab0d-9d265745017a)

## creation of the Model
![image](https://github.com/Darly09/barber_white_label_backend/assets/117688239/63194e96-9a01-412c-8c69-a2ede49b4032)

## endpoint login logic
![image](https://github.com/Darly09/barber_white_label_backend/assets/117688239/c601f2ad-c290-4e20-9325-b7fbf1754f6a)

## endpoint login
![image](https://github.com/Darly09/barber_white_label_backend/assets/117688239/dd442d52-462c-47ca-bce3-0839fdc95174)

2023-11-06 23:30 UTC, JSBHA approved these changes

2023-11-06 23:37 UTC, FelipeVelasquez1802 requested changes
# ⚠️Request changes

2023-11-06 23:37 UTC, FelipeVelasquez1802 commented on Model/Login.js
Please, add businnes logic of login

2023-11-07 01:55 UTC, FelipeVelasquez1802 approved these changes
# ✅Approved!

2023-11-07 01:57 UTC, merged