Feature/endpoint products mock
Darly09/barber_white_label_backend pull request #4
Opened 2023-11-14 00:13 UTC by JuanP0329

### 🎯 Milestone 

The endpoint is created to obtain the list of products.

### 🛠 Changes

Feat: model is created for the products
Feat: Moked products are created in the controller to be consumed in the product endpoint.
Feat: The endpoint view of the product list is created.
Refactor: Product endpoint router added

### 📘 Documentation 

- [ ] I have added or updated the documentation
- [x] No documentation update is required

2023-11-22 23:31 UTC, FelipeVelasquez1802 approved these changes
# ✅Approved!

2023-11-22 23:32 UTC, FelipeVelasquez1802 requested changes
# ❌Conflict!
@JuanP0329 please, check out this PR

2023-11-22 23:54 UTC, FelipeVelasquez1802 approved these changes
# ✅Approved!

2023-11-23 00:22 UTC, Dark1709 approved these changes

2023-11-23 00:24 UTC, merged