Feature/endpoint service by
Darly09/barber_white_label_backend pull request #7
Opened 2023-11-23 01:14 UTC by JSBHA

### 🎯 Milestone 

The endpoints of adding a new service and calling a service by id are created, the routes and the folder that will make the connection to the database are created.  

### 🛠 Changes

feat: A file is created in the controller folder called SelectServiceController.js which has the endpoint to only call one service per id 

feat:  A file is created in the controller folder called addServiceController.js which has the endpoint to create a new service  

feat: A folder called data is created containing a ServicesData.js file that contains the data and will make the connection to supabase. 

refactor: in the index.js the routers are added to add service and a response container is created for the endpoint of addServiceController.js

refactor:In the view folder ServiceView.js is updated with the controller paths of addServiceController.js and SelectServiceController.js a response container is created for all endpoints. 

### 📘 Documentation 

- [ ] I have added or updated the documentation
- [x] No documentation update is required

2023-11-23 01:41 UTC, JuanP0329 approved these changes

2023-11-26 23:53 UTC, JuanP0329 approved these changes

2023-11-28 00:02 UTC, FelipeVelasquez1802 requested changes
# ⚠️Request changes

@JSBHA please check out this comments

2023-11-28 00:02 UTC, FelipeVelasquez1802 commented on Controller/SelectServiceController.js
> +// endpoint para consumir un servicio
Please, delete this comment!

2023-11-28 00:02 UTC, FelipeVelasquez1802 commented on View/ServiceView.js
> +
Please, delete this lines

2023-11-28 00:02 UTC, FelipeVelasquez1802 commented on data/ServicesData.js
> +// //se creas const servicesMock para poder add el servicio
Please, delete this comment!

2023-11-28 00:02 UTC, FelipeVelasquez1802 commented on package.json
This file should not be deleted!

2023-11-28 00:48 UTC, FelipeVelasquez1802 approved these changes
# ✅Approved!

2023-11-28 01:08 UTC, merged